---
title: "Strumenti di poesia"
permalink: /personali/StrumentiPoesia/
---

## INTRODUZIONE METRICA

### Essenziale di linguistica

4 parti fondamentali:

1. **Fonetica/Fonologia**: studio dei suoni (foni) del linguaggio e di come vengono organizzati in unità distintive (fonemi) per formare parole
2. **Morfologia**: analizza la struttura interna delle parole (prefissi, suffissi, radici)
3. **Sintassi**: studio di come le parole vengono combinate per frasi e come le relazioni strutturali determinano il significato
4. **Semantica**: esamina il significato delle parole, frasi e testi

Con 2 elementi aggiuntivi:

- **Lessico**: insieme delle parole di una lingua
- **Pragmatica**: studio di come il contesto influenza significato e uso del linguaggio

### Strumenti della poesia

**Discorsi in prosa:** discorsi la cui struttura è motivata dal significato

**Discorsi in versi:** discorsi la cui struttura è motivata anche da principi formali estranei al significato

**Verso:** segmento del discorso organizzato secondo determinate regole. Unità minima della scansione del discorso in versi

**Strofe:** struttura intermedia di versi

**Forma strofica:** strofe dello stesso numero di versi, composti degli stessi tipi di versi nello stesso ordine e con eventuale stesso schema di rime (uso comune: strutture analizzabili in strofe secondo una struttura regolare)

**RITMO:** disporsi nel tempo di elementi riconoscibili e significativi (sillabe atone e toniche, suoni uguali, misure sillabiche)

**METRO:** norma entro la quale il ritmo si realizza.

- **Poesia regolare:** insieme elementi e regole che definiscono un modello
- **Poesia libera:** semplicemente il discorso si articola in versi

Esempio: settenario – metro: sette sillabe con sesta tonica, ritmo: disposizione degli altri accenti

**PROSODIA:** insieme delle regole riguardanti la quantità delle sillabe e la combinazione delle sillabe lunghe e brevi in piedi, metri e versi

#### CATALOGO DI FORME

- **Rime regolate**: a struttura fissa
- **Rime libere**: con struttura liberamente variabile
- **Rime mescolate**: sottoposte ad alcune regole

(forme regolate, fisse vs libere, generi e rime utilizzate, forme brevi, forme discorsive)

Relazione tra struttura sintattica e struttura metrica è una scelta di stile, non vincolato da regole precise

- Tendenzialmente di base è far **coincidere limite di verso con limite sintattico**

**Enjambement:** termine che indica mancata coincidenza tra unità sintattica e limite di verso (anche inarcatura, accavallamento e rompimento)

- **Rigetto:** parte breve di unità sintattica spezzata nel secondo verso
- **Controrigetto:** parte breve di unità sintattica che si colloca all'inizio del primo verso

L'enjambement è comune tra versi, raro tra altre unità metriche superiori.

Nelle forme strofiche è normale che la strofa termini con un limite sintattico "forte" o con la fine del periodo.

## CONTEGGIO DELLE SILLABE

**Sillaba:** unità ritmica della catena parlata (definizione semplicistica e funzionale). Costituita da almeno una vocale, eventualmente seguita da consonante o semiconsonante

**Isocromismo sillabico:** le sillabe percepite come se fossero tutte uguali per durata

**Sillabismo:** numero di una serie di sillabe

Due serie hanno lo stesso numero di sillabe se l'ultima tonica è nella stessa posizione (conti le sillabe fino all'ultima tonica)

**3 casi normali:**

- Uscita piana: ultima tonica + sillaba atona
- Uscita tronca: ultima tonica
- Uscita sdrucciola: ultima tonica + 2 sillabe atone
- Eccezionale: ultima tonica + diverse sillabe atone

Tutti questi casi sono considerati equivalenti in termini di sillabismo. Il numero di sillabe in un verso è determinato nel seguente modo:

numero di sillabe fino all'ultima tonica compresa + 1

In base a questa regola distinguiamo **parisillabi** e **imparisillabi**, che generalmente nella tradizione italiana vengono raramente mescolati.

### COMPUTO DELLE SILLABE ESEMPI

- **Tutte le vocali sono separate da almeno una consonante:** numero di vocali
  - `di me medesmo meco mi vergogno`
  - `di-me-me-de-smo-me-co-mi-ver-go-gno` (11 vocali = 11 sillabe, 10 tonica)

- Due o più vocali sono consecutive
  - All'interno di una parola:
    - **Dieresi:** nesso di 2 vocali → 2 sillabe (detto iato) – può essere grafica
    - **Sineresi:** nesso di 2 vocali → 1 sillaba
  - Tra due parole:
    - **Dialefe:** vocale finale e vocale iniziale → 2 sillabe (detto iato)
    - **Sinalefe:** vocale finale e vocale iniziale → 1 sillaba

- **Semiconsonante:** una i o u senza valore di sillaba, articolata come consonante (ostruzione aria espirata)
- **Semivocale:** analoga ma con minore ostruzione

### DIERESI E SINERESI

- Nessi vocale tonica + atona fine parola: mai/mia, lei/mie, voi/io, rea/reo, sua, sue, fui, suo
  - Fine verso: 2 sillabe
  - Interno: 1 sillaba (se dieresi di eccezione (tradizione petrarchista, dante) – 2 sillabe)
    - Dieresi d'eccezione più frequente davanti s + consonante

- Analogo trattamento nessi interni

- **Regola etimologica:** dieresi di nesso in 2 sillabe se deriva dal latino con 2 sillabe (anche derivazioni da altre lingue)
  - iè, uò derivanti da è, ae, ò (valgono sempre 1 sillaba)
  - `pie-de` ← `pe-dem`
  - `Lie-to` ← `lae-tum`
  - `Buo-no` ← `bo-num`
  - `Cava-lie-re` ← `chevalier`

#### NESSI TEORICAMENTE INSCINDIBILI

- **au:** regolarmente monosillabico in (laude, lauro, causa, pausa, aura)
- **eu:** generalmente monosillabico
- **i consonantica:** generalmente mai valore di sillaba
  - consonante + i + vocale derivante da cons. + l + vocale in latino
    - `pie-no` ← `ple-num`
    - `chia-ve` ← `cla-vem`
    - `fio-re` ← `flo-rem`
    - `tem-pio` ← `tem-plum`
      - Dieresi per ricavare parole sdrucciole di fine verso (esempio < exemplum)

- **i derivata da ri** (es aio ← arium)
- **u consonantica:** guerra, quasi, questo / lingua, sangue
- **Nesso grafico:** i come suono palatale di c, g, l (minaccia, saggio, figlio)
  - Generalmente 1, ma capita 2 con latinismi (savio, filio – derivazione di i vocale latina: religione in dante con 5 e non 4)

#### NESSI GENERALMENTE BISILLABICI

- **a, e, o + vocale tonica:**
  - `pa-e-se`, `pa-u-ra`, `ma-e-stro`, `be-a-to`, `le-a-le`, `le-o-ne`, `so-a-vi`

- **Nessi voc + i cons. + voc:**
  - `gio-ia`, `no-ia`, `-a-io`

#### NESSI SCANSIONE VARIABILE

- i, u atone + vocale tonica
  - Comune la dieresi, eccl iè, uò ← lat. È, ò
- nessi di due vocali atone diverse da i, u
  - forme collegabili con quelle con nesso tonico, spesso bisillabiche: `be-a-trì-ce` &larr; `be-à-to`, `pa-u-ro-se` &larr; `pa-ù-ra` (può anche essere monosillabico `pau-ro-se`)
- nessi di i atona + vocale atona in fine parola sono monosillabici (non sempre)
  - `pa-ia`
- nessi di vocale atona ≠ i + vocale atona in fine parola sempre monosillabici ma dieresi più frequente
  - `per-pe-tua`, ma a volte `mu-tu-a` (dieresi)

#### DIALEFE E SINALEFE

Generalmente vocale finale + vocale iniziale: sinalefe

- ahi quanto a dir qual era è cosa dura
  
> ahi<sub>1</sub> quan<sub>2</sub>to a<sub>3</sub> dir<sub>4</sub> qual<sub>5</sub> e<sub>6</sub> ra è<sub>7</sub> co<sub>8</sub> sa<sub>9</sub> du<sub>10</sub> ra<sub>11</sub>

Una vocale può venir sopressa mediante:

- **Elisione** della vocale finale `nostr' intellecto` &larr; `nostro intellecto`
- **Aferesi** della vocale iniziale `ne 'ngombra` &larr; `ne ingombra`
- **Crasi** di due vocali `ma` &larr; `ma a`

Per saper distinguere davvero elisione, aferesi e crasi dalla sinalefe è necessaria una copia dell'autore

Probabilità di condizioni in cui usare la dialefe, dalla più probabile alla meno probabile:

- dopo una vocale tonica o dopo una vocale tonica + atona
- dopo certi monosillabi (che, ma, se, o)
- tra vocale atona e vocale tonica
- tra due atone
- dopo una parola sdrucciola

Nessi vocale tonica + atona :

- sinalefe (sillaba sola)
- dialefe (due sillabe)

**anasinalefe o episinalefe**: dialefe tra due versi. Ripresa della figura latina della sinafìa.

#### ALTRE FIGURE

- **Elisione** soppressione vocale finale davanti all'iniziale della seguente (in alternativa a sinalefe)
- **Aferesi** soppressione vocale iniziale davanti alla finale della precedente (in alternativa a sinalefe)
- **Apocope** caduta della vocale finale `vuol` &larr; `vuole`
  - esempio: rima tronca in consonante ( `cuor / amor` &larr; `cuore / amore`)
  - **Epìtesi (paragoge)** aggiunta di una vocale finale `fue` &larr; `fu` 
    - evitare le finali tronche, costruire versi piani
- **Sincope** caduta di una vocale interna di parola `lettre` &larr; `lettere`
  - può essere apparente

#### CONVENZIONALITÀ DEL COMPUTO DELLE SILLABE

Desiderabile che esecuzione rispetti il computo sillabico

**Dieresi** e **dialefe** &rarr; più semplice, lieve stacco nella pronuncia delle vocali che formano due sillabe diverse.

Può esserci problema di riconoscimento se manca l'indicazione grafica (ä, ë, ï, ö, ü)

**Sineresi** &rarr; più difficile, esempio (pau-ra, gioia, aio come unica sillaba). Possibile pronuncia accelerata

**Sinalefe** &rarr; più difficile, pronuncia separata per distinguere da elisione.

**Casi marcati**:

- sineresi di un nesso di regola bisillabico
- dieresi di un nesso di regola monosillabico
- dialefe

Questi vanno segnalati nella pronuncia.

La sillabazione della lingua poetica è convenzionale, presuppone un pubblico che condivida un sistema di regole distinto con l'autore. Alla fine si tratta di un fatto di cultura

#### CESURA

La cesura latina era un limite di parola che cadeva all'interno di un piede (unità metrica) inziché alla fine

Nella metrica italiana i versi doppi sono articolati in due parti, detti emistichi.

**Cesura**: separazione fra due emistichi di un verso

**Emistichio (mezzo verso)**: parte di verso che precede o segue la cesura

Generalmente gli emistichi nei versi doppi sono trattati come versi veri e propri.

- (quasi) mai sinalefe tra emistichi
- primo emistichio tronco, piano o sdrucciolo senza alterare misura del totale (non frequente nella metrica moderna)

**Cesura come fatto metrico**: propria dal décasyllabe francese/provenzale, due emistichi di 4 e 6 sillabe (4^a^ e 6^a^ tonica). Serve a riconoscere intuitivamente la misura del verso.

**Cesura come fatto sintattico/ritmico**: pausa sintattica o di intonazione, solitamente circa a metà verso, in modo che le due parti siano ritmicamente simili a un quinario e settenario. Non è obbligatoria

La funzione metrica della cesura si è persa nella metrica italiana, in quanto sostituita dalla disposizione degli accenti. L'endecasillabo può oscillare tra divisione interna in emistichi o andamento ritmico unitario. Questo fatto è stato favorito dalla presenza di parole sdrucciole assenti in francese e provenzale.

#### ISOSILLABISMO E ANISOSILLABISMO

**isosillabismo**: tutti i versi hanno lo stesso numero di sillabe, nella tradizione italiana è tipico

**ipermetro**: verso che eccede la misura prevista
**ipometro**: verso che non raggiunge la misura prevista

**anisillabismo:** dato un verso di base, una certa varianza del numero di sillabe non altera forma metrica

## L'ACCENTO

### Sillabismo e accento

La metrica italiana considera anche la posiuzione dell'ultima sillaba tonica, perchiò è definibile _sillabico-accentuativa_

**accento di intensità, dinamico**: implica un aumento di forza nella pronuncia della sillaba, che si distingue dalle altre per maggiore intensità

Tra accenti pertinenti nel verso e quelli rilevabili non c'è piena coincidenza, raramente un accento metrico cade su una sillaba che sarebbe atona in prosa. Per questi alcuni parlano di **ictus** invece che di accento

#### accenti obbligatori, principali, secondari

- **accenti del verso**: sillabe che occupano certe posizioni sono toniche

- **accenti obbligatori**: posizioni che devono essere occupate da una sillaba tonica secondo la norma adottata

- **accenti principali**: accenti la cui presenza o assenza è un elemento distintivo tra un verso istituzionale o meno

- **accenti secondari**: accenti che non sono obbligatori per il metro ma che contribuiscono a definire il ritmo del verso

**schema accentuativo**: disposizione degli accenti nel verso

#### versi ad accentazione fissa o variabile

- **versi ad accentazione fissa**: accenti obbligatori in posizioni fisse
  - decasillabo (3^a^, 6^a^, 9^a^); novenario (2^a^, 5^a^, 8^a^); ottonario (3^a^, 7^a^); senario (2^a^, 5^a^);

- **versi ad accentazione variabile**: versi con diverse disposizioni di accenti non obbligatori
  - endecasillabo (su 4^a^ o 6^a^ oltre la 10^a^); settenario (una delle prime 4 sillabe tonica + 6^a^); quinario (1^a^ o 2^a^ + 4^a^)

- **versi distinti dal solo schema accentuativo**: generalmente due versi con lo stesso numero di sillabe sono sostituibili tra loro, anche se presentano una diversa disposizione degli accenti non obbligatori. Rari i casi in cui non è così

### Interpretazione ritmica del verso

Il profilo ritmico del verso ha i suoi punti di riferimento negli accenti obbligatori e principali, ma soprattutto nell'ultimo accento.

Esiste una tensione tra fra discorso in versi e lingua naturale.

Prendiamo il caso di un limite di verso che separa due elementi sintattici strettamente connessi (aggettivo e il suo sostantivo)

- pronuncia legata: distrugge il verso
- pronuncia staccata: risulta innaturale

Questa tensione tuttavia consente di usare come strumento del ritmo la distribuzione delle pause sintattiche.

Ricordiamo che ogni forma di esecuzione (lettura ad alta voce) è corretta, mentre nella produzione del testo interviene un modello di forma metrica presente nell'autore.

**regole metriche**: descrivono ciò che nel modello è il minimo essenziale per la correttezza metrica.

Un verso è corretto rispetto al suo modello se esiste almeno un'esecuzione possibile che vi corrisponda.

#### Come si individuano gli accenti

Esiste un problema legato ai diversi schemi accentuativi.

Un criterio è assumere che normalmente l'accento metrico coincide con un accento di parola.

**atoni**:

- articoli
- preposizioni
- congiunzioni
- pronomi personali monosillabici (io, tu, lui) seguiti dal verbo
- non (se in posizione non enfatica)
- aggettivi personali monosillabici (mio, tuo) in posizione debole
  - mia vita &rarr; atono
  - vita mia &rarr; tonico
- ausiliari di una sillaba seguiti da participio (è stato)
- ausiliari di due sillabe se l'accento viene a contatto con quello del participio
  - l'avea fatto &rarr; atono
  - l'abbia perduto &rarr; tonico
- aggettivi di una sillaba (gran, bel, buon) seguiti dal sostantivo

#### Spostamenti d'accento

**diàstole**: spostamento dell'accento in avanti

**sìstole**: spostamento dell'accento all'indietro

In passato avveniva per presenza di doppie forme di parole proprie della lingua poetica.

#### Accenti consecutivi

Esistono teorie prosodiche secondo cui non sono possibili due toniche né tre atone consecutive.

Accenti consecutivi possono essere eseguiti con una lieve pausa fra l'uno e l'altro, in caso di più atone consecutive ci si potrà appoggiare con la voce a una delle sillabe.

## I VERSI ITALIANI

### Endecasillabo

ultima sillaba tonica in 10^a^ posizione

- **canonico**: almeno una tra 4^a^ o 6^a^ toniche + 10^a^
  - **a minore**: 4^a^ + 10^a^ (ritmo iniziale quinario)
  - **a maiore**: 6^a^ + 10^a^ (ritmo iniziale settenario)
- **non canonico**: 4^a^ e 6^a^ atone

### Decasillabo

ultima sillaba tonica in 9^a^ posizione

- **forma accenti fissi**: 3^a^ + 6^a^ + 9^a^ toniche

> S'ode a dé$_3$stra uno squillo di tròmba,
> a sinís$_3$tra rispón$_6$de uno squillo

### Novenario

ultima sillaba tonica in 8^a^ posizione

- **forma accenti fissi**: 2^a^ + 5^a^ + 8^a^ toniche

In Pascoli del tipo 2^a^ + 5^a^ + 8^a^ e 3^a^ + 5^a^ + 8^a^

### Novenario Doppio

Due novenari nello stesso verso

### Ottonario

ultima sillaba tonica in 7^a^ posizione

- **forma accenti fissi**: 3^a^ + 7^a^ toniche

In Pascoli del tipo 3^a^ + 7^a^ e 1^a^ + 4^a^ + 7^a^

### Ottonario Doppio

Due ottonari nello stesso verso

### Settenario

ultima sillaba tonica in 6^a^ posizione

- **forma eccezionale**: 5^a^ + 6^a^ toniche

Frequente combinazione settenari e endecasillabi

### Settenario Doppio (alessandrino o martelliano)

due settenari nello stesso verso, diverse tipologie

- settenario sdrucciolo + settenario piano
- settenario piano o sdrucciolo + settenario
- martelliano: settenario piano + settenario piano

### Senario

ultima sillaba tonica in 5^a^ posizione

- **forma normale**: 2^a^ + 5^a^ toniche
- **forma eccezionale**: altra sillaba tonica non in seconda posizione

### Senario Doppio

Due senari nello stesso verso. Entrambi con 2^a^ + 5^a^

### Quinario

ultima sillaba tonica in 4^a^ posizione

Generalmente toniche 1^a^ o 2^a^, eccezionalmente la 3^a^ oppure unicamente la 4^a^

### Quinario Doppio

Si distingue dal decasillabo perché la divisione è costante e accento cade sempre sulla 4^a^

### Quadrisillabo

ultima sillaba tonica in 3^a^ posizione

### Trisillabo

ultima sillaba tonica in 2^a^ posizione

## LA RIMA

### Caratteristiche generali e tipologie di schemi delle rime

**rima**: identià di suono della parte finale di duo o più parole, a partire della vocale tonica compresa (o di due o più versi sempre a partire dalla vocale tonica compresa)

può avere funzione **demarcativa** da un verso all'altro, soprattuto nella poesia anisosillabica.

Nella poesia isosillabica (verso percepibile in numero di sillabe e accenti), la funzione demarcativa è minore, se non all'interno del verso.

**schema delle rime**: disposizione delle rime, uno degli elementi di maggiore rilievo nella costruzione di strutture strofiche.

**rima baciata o a coppie o accoppiata**: AA BB CC
**rima alternata o incrociata**: ABAB CDCD
**rima incrociata o chiusa o abbracciata**: ABBA CDDC
**rima incatenata**: ABAB BCBC
**rima costante**: AAAA

### Funzione ritmica o associativa

Le ripetizione di serie di suoni servono a dare ritmo al testo e a associare tra loro due o più parole, relazionandole anche dal punto di vista semantico.

**rima facile**: scarso impegno stilistico, di cui sono disponibili molte parole

- **desinenziale**: parole di uguale desinenza (mentire / sentire)
- **suffissale**: parole di uguale suffisso (avverbi in -mente)

**rima difficile**: rima con poche paroli disponibili

**rima derivativa**: fra due parole di cui una deriva dall'altra (degna / disdegna), anche con con derivazione apparente (membra / rimembra)

**rima inclusiva**: una parola in rima è contenuta nelle altre (arte / Marte), anche in assenza di derivazione vera o falsa (carte / parte)

### identità di suoni e tipologie

**rima perfetta**: identità di tutte le vocali e consonanti a partire dall'ultima tonica

**rima imperfetta**: rima non perfetta

- **assonanza**: identità rigorosa delle sole vocali (dice / venisse)
  - **assonanza imperfetta**: uguale soltanto ultima vocale tonica
- **consonanza**: uguali soltanto le consonanti o manca uguaglianza dell'ultima tonica, raramente in luogo della rima ma più spesso per collegare fra loro serie di rime diverse.

L'assonanza al posto della rima non è necessariamente segno di trascuratezza.

NOTA: il concetto di identità non è unicamente fonetica ma anche culturale: in italiano _è_ aperta fa rima con _é_ chiusa. Nelle metriche romanza e provenzale per esempio non è così. Pare che questo sia dovuta anche all'influenza del siciliano. Un esempio di rima culturale è la rima siciliana, uscita dall'uso odierno.

### Rime piane, tronche, sdrucciole

**rima piana**: rima tra due parole piane (ultima tonica in penultima sillaba)

**rima tronca**: rima tra due parole tronche (ultima tonica in ultima sillaba)
  
**rima tronca in consonante**: rima tra due parole tronche che terminano con la stessa consonante (ultima tonica in ultima sillaba): amor/finir/man

**rima sdrucciola**: rima tra due parole sdrucciole (ultima tonica in terzultima sillaba)

### Rime tecniche

**rima tecnica**: tipologie di rime ricavate da tipologie particolari (è un insieme di tipologie di rime)

**rima ricca**: identità di uno o più suoni precedenti l'ultima vocale tonica: sentero/altero

**rima ricca contraffatta**: si estende al di là delle parole stesse: l'ore/colore

**rima grammaticale**: rapporto di derivazione o parentela grammaticale istituito fra le due serie di rime:
clami/clama/ch'ami/ch'ama

**rima equivoca**: identità di suono delle parole in rima

**rima identica**: una parola rima con se stessa (indice di scarsa capacità tecnica).

Di regola le parole omofone devono differire tra loro per

- significato
- categoria grammaticale
- genere, numero, modo verbale

**rima equivoca contraffatta**: equivocazione ottenuta sommando due parole (m'ai / mai)

**rima composta(spezzata, franta, rotta)**: parola in rima ottenuta artificiosamente sommando parole distinte (sòl tre /oltre/poltre)

  in questo caso l'alterazione dell'accento consiste nel subordinare all'accento che cade nella posizione richiesta quello del monosillabo successivo

**rima equivoca contraffatta (con alterazione d'accento)**: par l'à (da scandire pàrla) / parla

**rima per l'occhio**: identià nella parte finale di due versi è grafica. Tuttavia la versione propriamente detta richiederebbe uno spostamento dell'accento di parola. 

- caso uno: mando / comandò (accentato comàndo)
- caso due: perché (accentato pérche)/ cerche

**rima per l'occhio irriducibile**: identità puramente convenzionale (perché / cerche)

**rima in tmesi**: divide una parola in fine di verso (... differente - mente ... / ... lente)

**rima ipermetra**: sillaba in più che riguarda la rima e non il verso (tACIta / tenACI)

### Rima interna

Le rime possono cadere anche all'interno del verso.

**rima al mezzo**: divide il verso in emistichi (in cesura nell'endecasillabo)

**rima interna**: non corrisponde a tale divisione

Non impediscono mai la sinalefe

**rima sineretica**: forma bisillabica di un nesso di vocale atonica + atona (leggiadria / svia)

> che leggiadria
> di svia cotanto e più che quant'io conto

**rima interna/al mezzo con apocope**: dottare/portar

> ché più onta che mort'è da dottare
> e portar - disragion più che dannaggio.

**rima irrelata**: verso che non rima con nessun altro (verso irrelato). Concetto che ha senso soltanto se il verso è parte di uno schema di rime che prevede/ammette versi non rimati in certe posizioni.

## FORME REGOLATE E FORME FISSE

## FORME LIBERE METRICA TRADIZIONALE

## METRICA BARBARA

## FORME METRICHE POESIA ITALIANA

## METRICA LIBERA MODERNA