---
layout: default
title: Basi di dati
permalink: /universita/basiDati/
---

## Introduzione

Caratteristiche distintive di un database:

- **persistenza**
- **mole**
- **globalità**

Caratteristiche generali di un sistema informatico:

- indipendenza dei dati (facilità uso)
- strutture di indicizzazione e ottimizzazione (efficienza operazioni di accesso)
- convenienza (efficacia)

persistenza del database: salvataggio in memoria secondaria e esistenza indipendente dai programmi che lo usano

mole: gestione di grandi quantità di dati, ovvero superiore alla porzione di ram dedicata, particolare attenzione all'efficienza delle operazioni di trasferimento dati

globalità dei dati: necessità di disciplinare l'uso dei dati, gestendo diritti di accesso e garantendo privatezza e integrità da eventuali conflitti

### definizione

Base di dati: collezione di dati usata per rappresentare informazioni di interesse per un dato sistema informativo

collezione di dati gestita da un DataBase Management System (DBMS)

Le basi di dati supportano astrazioni sui dati:

- livello fisico
- livello logico
- livello delle viste

Modello dei dati: collezione di strumenti concettuali per descrivere i dati, le loro relazioni e i vincoli di consistenza

possono essere distinti in:

- modelli basati sull'identità degli oggetti
- modelli basati sui valori degli oggetti

Oppure in:

- modelli basati sugli oggetti
- modelli basati sui record

Parlando di basi di dati, è importante distinguere tra:

- schema
- istanza

