---
title: Economia Aziendale
description: "Appunti di economia aziendale del 1 anno di economia e commercio"
permalink: /wiki/universita/economiaAziendale/
categories: [università, economia]
---

## Rilevazioni e determinazioni quantitative d'azienda

I metodi per le rilevazioni quantitative d'azienda si dividono in due grandi categorie:

- metodi extra-contabili (o statistici)
- metodi contabili (studiati dalla Ragioneria)

I metodi contabili utilizzano il *conto* come strumento di rilevazione. Il conto può essere inteso in

- *senso sostanziale*: insieme di scritture riferite a un dato oggetto, generalmente riferiti a quantità monetarie (conti a valori) o a quantità fisiche (conti a quantità). L'omogeneità dei valori è data dall'unità di misura, la *moneta di conto*. Le quantità rilevate sono *variazioni di conto*
- *senso formale*: prospetto a due sezioni che accoglie valori omogenei riferiti a un dato oggeto. In una sezione sono rilevate le *variazioni in aumento* e nell'altra le *variazioni in diminuzione*.

  - **dare**: sezione in cui sono rilevate le variazioni in aumento
  - **avere**: sezione in cui sono rilevate le variazioni in diminuzione

Esistono diverse forme grafiche del conto, suddivise in:

- conti a sezioni divise e contrapposte
- conti a sezione divise e accostate
- conti in forma scalare

I conti a sezioni divise e contrapposte sono caratterizzati da due sezioni, una accanto all'altra, con la precisazione dei seguenti elementi:

- data dell'operazione
- numeri di riferimento con cui si collega l'operazione ad altri conti
- descrizione sintetica dell'operazione
- valori di conto




