---
title: Appunti di università
permalink: /wiki/universita/
search: false
draft: true
---

## 1 anno informatica

- [Analisi matematica]
- [Programmazione e laboratorio](programmazione.qmd)
- [Architettura degli elaboratori](./architettura.qmd)
- [Matematica Discreta](./MatematicaDiscreta.qmd)
- [Algebra lineare](./algebraSchemi.qmd)
- [Fisica](./fisica_2026/fisica26.qmd)

extra:

- [Matematica di base](./matematica/matematica.qmd)
- [Fisica_Santi](./fisica/fisica.qmd)

## 2 anno informatica

- [Algoritmi e strutture dati]
- [Sistemi operativi](./sistemiOperativi.qmd)
- [Statistica]
- [Calcolo scientifico]
- [Logica]
- [Fondamenti di informatica]

OOp:

- [Programmazione a oggetti](./oop.qmd)
- [Terra esempio oop](./Terra.qmd)
- [Barche esempio oop](./barcheoop.qmd)
- [voli esempio oop](./voli.qmd)

## 3 anno informatica

- [Reti di calcolatori]
- [Ingegneria del software](./IngegneriaDelSoftware.qmd)
- [Basi di dati](./BasiDati.qmd)
- [Interazione uomo-macchina]
- [Linguaggi di programmazione]

## Extra programma

- [Scienza dei dati]
- [Machine Learning]
- [Internet e tecnologie web]
- [Analisi Matematica 2]
- [plc]
- [Sistemi embedded]

## Da Economia e Commercio

1 anno:

- [Storia economica]
- Matematica generale: in analisi 1 e altre materie
- [Economia aziendale]
- [Microeconomia](./microeconomia.qmd)
- [Diritto privato]

2 anno:

- [Economia e gestione delle imprese]
- [Macroeconomia]
- [Economia industriale]
- [Matematica per le applicazioni economiche]
- [Statistica economica]
- [Diritto del lavoro]

3 anno:

- [Politica economica e monetaria]
- [Econometria]
- [Sociologia]
- [Strumenti statistici per l'economia]
- [Economia degli intermediari finanziari]
- [Diritto commerciale]

## Altri appunti

- Roba di diritto europeo (istituzioni) e diritto pubblico (istituzioni)
